# https://github.com/marketplace/actions/build-with-gradle#the-dependency-submission-action
name: Dependabot Submission
run-name: Running Dependabot Dependency Submission
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
